services:
    # redis:
    #     image: redis:alpine
    #     restart: unless-stopped
    #     ports:
    #         - '6379:6379'
    #     networks:
    #         - eliza_network

    db:
        image: pgvector/pgvector:0.8.0-pg17
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: eliza
            POSTGRES_USER: eliza
            POSTGRES_PASSWORD: eliza
        volumes:
            - /home/ubuntu/eliza/packages/adapter-postgres:/mnt/adapter-postgres
            - /home/ubuntu/eliza/db_data:/var/lib/postgresql/data
        networks:
            - eliza_network


networks:
    eliza_network:
        driver: bridge
