services:
    # redis:
    #     image: redis:alpine
    #     restart: unless-stopped
    #     ports:
    #         - '6379:6379'
    #     networks:
    #         - eliza_network

    db:
        image: pgvector/pgvector:0.8.0-pg17
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: eliza
            POSTGRES_USER: eliza
            POSTGRES_PASSWORD: eliza
        volumes:
            - ./packages/adapter-postgres:/mnt/adapter-postgres
            - ./db_data:/var/lib/postgresql/data
        networks:
            - eliza_network

    # rabbitmq:
    #     image: rabbitmq:management-alpine
    #     restart: unless-stopped
    #     ports:
    #         - '15672:15672'  # RabbitMQ management UI (HTTP)
    #         - '5672:5672'    # RabbitMQ AMQP protocol port
    #     environment:
    #         RABBITMQ_DEFAULT_USER: guest
    #         RABBITMQ_DEFAULT_PASS: guest
    #     volumes:
    #         - ./rabbitmq_data:/var/lib/rabbitmq  # Volume lưu trữ dữ liệu RabbitMQ
    #     networks:
    #         - eliza_network

networks:
    eliza_network:
        driver: bridge
